name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: php v
        run: php -v

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-node-${{ matrix.operating-system }}-7.2-${{ hashFiles('**/composer.lock') }}


      - name: Setup PHP - ${{ matrix.operating-system }} - 7.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          tools: composer

      - name: php v
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test


      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-node-${{ matrix.operating-system }}-7.3-${{ hashFiles('**/composer.lock') }}


      - name: Setup PHP - ${{ matrix.operating-system }} - 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer

      - name: php v
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test

